### ISSUE TITLE
Peer to peer review, October 4th, 2022

### ISSUE THREAD

**Issue by Olivier-Kango** [eerapheal/awesomebook-ES6#2]
#### After checking your code, we found that your code:

:heavy_check_mark: is clean.
:heavy_check_mark: Very good accessibility, ⁣
:heavy_check_mark: No linter errors.

**Comment by eerapheal** [comment]
## Thanks for the review.

**Comment by eerapheal** [comment]
## Thanks for the review.

**Comment by eerapheal** [comment]
## Thanks for the review.
